### PR TITLE
Refactor tolerations arguments for the install command

### PR DESCRIPTION
**Pull request by fernandocarletti**
Hello! I did dome refactoring on how the tolerations are passed as an argument to Venona. I saw that despite being documented as a JSON string, it was actually expecting for a file. I changed it to support both formats. If the argument is prefixed with an `@` it will now load a file.

I also ran `go fmt` in the whole project, adding the `make fmt` command as a shortcut, so I suggest checking the commits separately, since just two of them are really related to this PR: 605ded0 and 1616039.

The tolerations were missing in the `dind-lv-monitor` DaemonSet and `dind-volume-provisioning`, not allowing them to be scheduled in the nodes with the `nodeSelector` that have the custom `tolerations`.

The only issue I still see is that the tolerations are not being added to the "dynamic" pods. I believe it is something done server-side, since the [build annotations are sent to the Codefresh API](https://github.com/codefresh-io/venona/blob/master/venonactl/cmd/install.go#L193). I suppose the tolerations should be sent as well, right?

### CODE REVIEW

**Comment by fernandocarletti** [comment]
@oren-codefresh It may break BC since passing the file path should now be prefixed with `@`. Isn't it safer to bump a minor version, `0.30.0`?

**Comment by oren-codefresh** [comment]
@fernandocarletti , Good idea, please bump to 0.30.0

**Comment by oren-codefresh** [comment]
verify

**Comment by fernandocarletti** [comment]
Done!

**Comment by oren-codefresh** [comment]
@fernandocarletti , can you also update the VERSION file with the same version ? Thanks a lot

**Comment by fernandocarletti** [comment]
Done!

**Comment by olegsu** [comment]
LGTM

**Pull request merged**
