### PR TITLE
[CR-7214] updated apiVersion field in rbac manifests

### PR DESCRIPTION
**Pull request by mikhail-klimko**

### CODE REVIEW

**Comment by TedSpinks** [comment]
Hey @mikhail-klimko why did we need to update apiVersion - was it for compatibility with newer K8s versions? What do the venona VERSION files do?

**Comment by mikhail-klimko** [comment]
> Hey @mikhail-klimko why did we need to update apiVersion - was it for compatibility with newer K8s versions? What do the venona VERSION files do?
Hi @TedSpinks 

Yes, it is for future compatibility:
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122

Bumped VERSION files for CD pipeline as described by @roi-codefresh

**Review by TedSpinks — APPROVED** [review]
Gotcha! Looks good to me.

**Comment by roi-codefresh** [comment]
ty guys!

**Pull request merged**
